org.gradle.jvmargs=-Xmx1024m -XX:+UseSerialGC -Dfile.encoding=UTF-8
org.gradle.java.home=C:\\Users\\sushant\\.jdks\\jbr-17.0.14
org.gradle.parallel=false
org.gradle.workers.max=1
kotlin.daemon.jvmargs=-Xmx768m
android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official
android.nonTransitiveRClass=true
